# Pad Nested Tensor (ESSENTIAL)

- Tensor의 길이가 달라서 list로 넣었을때
- 길이가 다른 tensor를 padding을 이용해서 강제로 동일 길이로 맞출때
- 이러한 방법을 쓰면 float나 na값을 tensor에 넣어서 list와 tensor 혼종을 다 tensor로 만들수 있다.

- float를 이용한 nesting과 padding
https://stackoverflow.com/questions/75104089/how-to-pad-a-tensor
https://pytorch.org/docs/stable/nested.html

> torch.nested.nested_tensor(list of tensors)

> torch.nested.to_padded_tensor(nested tensor)

In [26]:
import torch

#=======list[list]] to nested tensor and pad
a = [
    [101, 103],
    [101, 1045, 223],
    [101, 777, 665, 889],
    [101, 888]
]
a = torch.nested.nested_tensor(list(map(torch.tensor, a)))
print("1. nested", "\n", a)

b = torch.nested.to_padded_tensor(a, -1)
print("2. nested and padded", "\n", b, "\n", b.shape)

1. nested 
 nested_tensor([
  tensor([101, 103]),
  tensor([ 101, 1045,  223]),
  tensor([101, 777, 665, 889]),
  tensor([101, 888])
])
2. nested and padded 
 tensor([[ 101,  103,   -1,   -1],
        [ 101, 1045,  223,   -1],
        [ 101,  777,  665,  889],
        [ 101,  888,   -1,   -1]]) 
 torch.Size([4, 4])


In [22]:
import torch
#=========list[tensor] to nested and pad

c = [torch.rand(i,4) for i in (3,4,5)]
c = torch.nested.nested_tensor(c)
d = torch.nested.to_padded_tensor(c, 0)
print("1. nested", "\n", c)
print("2. nested and padded", "\n", d, "\n", d.shape)

1. nested 
 nested_tensor([
  tensor([[0.5400, 0.7817, 0.5525, 0.4884],
          [0.2663, 0.7654, 0.5359, 0.8745],
          [0.8788, 0.3291, 0.6083, 0.3404]]),
  tensor([[0.6354, 0.4498, 0.9036, 0.7623],
          [0.6869, 0.8314, 0.9926, 0.3313],
          [0.2413, 0.5132, 0.8960, 0.8628],
          [0.5814, 0.9064, 0.8649, 0.0736]]),
  tensor([[0.5381, 0.1957, 0.3582, 0.9246],
          [0.0223, 0.3679, 0.6802, 0.3811],
          [0.5316, 0.0475, 0.2689, 0.3855],
          [0.0865, 0.6239, 0.2449, 0.3130],
          [0.4752, 0.8533, 0.9366, 0.4470]])
])
2. nested and padded 
 tensor([[[0.5400, 0.7817, 0.5525, 0.4884],
         [0.2663, 0.7654, 0.5359, 0.8745],
         [0.8788, 0.3291, 0.6083, 0.3404],
         [0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000]],

        [[0.6354, 0.4498, 0.9036, 0.7623],
         [0.6869, 0.8314, 0.9926, 0.3313],
         [0.2413, 0.5132, 0.8960, 0.8628],
         [0.5814, 0.9064, 0.8649, 0.0736],
         [0.0000, 0.0000

In [30]:
a = torch.randn(3, 4, 5)
b = torch.mean(a, 0)
print(b.shape)

torch.Size([4, 5])
